version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: info_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rust_app:
    image: crud:latest
    ports:
      - "6001:6001"
    environment:
      DATABASE_URL: postgresql://postgres:abc123@postgres:5432/info_db
    depends_on:
      - postgres